# -*- coding: utf-8 -*-
"""Entertainer Data Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1xKMwqMkzh4Poxoa0kwyu5r1-egUuI1
"""

import pandas as pd

"""**BASIC INFORMATION OF ENTERTAINMENT**"""

import pandas as pd

# Load the Excel file into a pandas DataFrame
excel_file = pd.read_excel('/Entertainer - Basic Info.xlsx')

# Save the DataFrame to a CSV file
excel_file.to_csv('Basic Info.csv', index=False)

print('Conversion complete.')

filepath = '/content/Basic Info.csv'

data = pd.read_csv(filepath)

data.head()

data

data.shape

data.dtypes

data.size

data.isnull()

data.info()

data['Entertainer'].describe()

count_Adele =len(data['Entertainer'][data['Entertainer'] =='Adele'])
count_Bob =len(data['Entertainer'][data['Entertainer'] =='Bob'])

print("As per dataset, we have %d records Entertainer as 'Adele'and %d as 'Bob'" %(count_Adele,count_Bob))

data.describe()

data = data[data['Entertainer'] != 'Adele']

data[data['Entertainer'] == 'Adele'].mean()

import pandas as pd

# Load the Excel file into a pandas DataFrame
excel_file = pd.read_excel('/content/Entertainer - Breakthrough Info.xlsx')

# Save the DataFrame to a CSV file
excel_file.to_csv('Breakthrough Info.csv', index=False)

print('Conversion complete.')

"""**FOR BREAKTHROUGH INFORMATION OF ENTERTAINMENT**"""

import plotly.express as px
df = pd.read_csv("/content/Breakthrough Info.csv")

df.shape

df.columns

x = df.groupby(['Breakthrough Name']).size().reset_index(name = 'counts')
print(x)

pieChart = px.pie(x, values='counts' , names='Breakthrough Name' , title='Several Songs')
pieChart.show

import plotly.graph_objects as go

# Create a simple scatter plot
fig = go.Figure(data=go.Scatter(x=[1, 2, 3], y=[4, 1, 3]))

# Display the figure
fig.show()

df['Year of First Oscar/Grammy/Emmy'] = df['Year of First Oscar/Grammy/Emmy'].fillna('Year of First Oscar/Grammy/Emmy not specified')
df.head()

Entertainer_list = pd.DataFrame()
print(Entertainer_list)

Entertainer_list = df.Entertainer.str.split(',', expand=True).stack()
print(Entertainer_list)

Entertainer_list = Entertainer_list.to_frame()
print(Entertainer_list)

"""**Last Work Information For Entertainment**"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly.express as px

# Load the Excel file into a pandas DataFrame
excel_file = pd.read_excel('/content/Entertainer - Last work Info.xlsx')

# Save the DataFrame to a CSV file
excel_file.to_csv('Last work.csv', index=False)

print('Conversion complete.')

filepath = '/content/Last work.csv'

df.columns

df.head()

plt.figure(figsize =(10, 6))
df.groupby('Year of Breakthrough/#1 Hit/Award Nomination')

df['Year of First Oscar/Grammy/Emmy'].dtype
df['Year of Breakthrough/#1 Hit/Award Nomination'].dtype

df['Year of First Oscar/Grammy/Emmy'] = pd.to_numeric(df['Year of First Oscar/Grammy/Emmy'], errors='coerce')
df['Year of Breakthrough/#1 Hit/Award Nomination'] = pd.to_numeric(df['Year of Breakthrough/#1 Hit/Award Nomination'], errors='coerce')

df.insert(3, 'Best year' , df['Year of First Oscar/Grammy/Emmy'] - df['Year of Breakthrough/#1 Hit/Award Nomination'])

df['Best year'].dtype

df['Best year'].plot(kind='hist', bins=10)
plt.xlabel('Years')
plt.ylabel('Frequency')
plt.title('Distribution of Best Year')
plt.show()

df1 = df[['Entertainer','Year of Breakthrough/#1 Hit/Award Nomination','Breakthrough Name','Year of First Oscar/Grammy/Emmy']]

df1.hist(bins = 20, figsize =(14,12))

df.Entertainer.value_counts()

import pandas as pd

# Access the Breakthrough Name column:
df["Breakthrough Name"]

# Apply the max() function to the Breakthrough Name column:
df["Breakthrough Name"].max()

import pandas as pd

# Access the Year of First Oscar/Grammy/Emmy column:
df["Year of First Oscar/Grammy/Emmy"]

# Apply the max() function to the Year of First Oscar/Grammy/Emmy column:
df["Year of First Oscar/Grammy/Emmy"].max()

# Access the Year of Breakthrough/#1 Hit/Award Nomination column:
df["Year of Breakthrough/#1 Hit/Award Nomination"]

# Apply the max() function to the Year of Breakthrough/#1 Hit/Award Nomination column:
df["Year of Breakthrough/#1 Hit/Award Nomination"].max()

import pandas as pd

# Sort the DataFrame by multiple columns in ascending order:
df.sort_values(by=["Year of First Oscar/Grammy/Emmy", "Year of Breakthrough/#1 Hit/Award Nomination"], ascending=True)

df2 = df.groupby('Year of Breakthrough/#1 Hit/Award Nomination')['Year of First Oscar/Grammy/Emmy'].sum().plot(kind = 'line')